# Example plant watering automation 

# The Capacitive sensor readings fluctuate a bit -
# triger is set to only work when the readings have been
# consistently below the moisture threshhold configured 
# status variable configured in ESPHome YAML (See readme)
# <Home assistant device specific ID> created by Home Assistant 
# so dont paste over it!


alias: Water the Plant
description: "Waters the plant when soil is dry"
trigger:
  - type: not_moist
    platform: device
    device_id: <Home assistant device specific ID>
    entity_id: binary_sensor.soil_moisture
    domain: binary_sensor
    for:
      hours: 0
      minutes: 30
      seconds: 0
      
# Falesafe configuration prevents the automation running
# if watering has been triggered 4 times in the last 4 hours
# mitigates issues where the water tank is empty (project does
# not include a sensor to directly detect this) or the water pipe 
# may have moved and watering outside the pot.
# for this to work the history_stat sensor needs to be added to the 
# configuration.yaml file (see readme.txt and example folder)
condition:
  - condition: numeric_state
    entity_id: sensor.plant_watering_last_4_hours
    below: "4"
# Added a condition that the pump must have been off for 1 hour
# This prevents the automation repeatedly triggering and drenching
# the plant / room before the soli can absorb the water from a previously
# triggered watering cycle.
  - condition: device
    type: is_off
    device_id: <Home assistant device specific ID>
    entity_id: switch.water_pump
    domain: switch
    for:
      hours: 1
      minutes: 0
      seconds: 0
      
# LED light switches on to indicate pump is running
# M5 Atom LED is not that bright, but useful when you hear
# a slight trickeling noise from the pump to be able to 
# to see a light from the general direction of the sound!
action:
  - type: turn_on
    device_id: <Home assistant device specific ID>
    entity_id: light.fastled_light
    domain: light
    flash: short
    brightness_pct: 100
# Switches on pump for specified time, delay value should be 
# ajusted to suit your specific watering requirements based on 
# plant size/ pot size/ soil moisture requirements
  - type: turn_on
    device_id: <Home assistant device specific ID>
    entity_id: switch.water_pump
    domain: switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 
    entity_id: switch.water_pump
    domain: switch
# Switches off light when watering cycle complete
  - type: turn_off
    device_id: <Home assistant device specific ID>
    entity_id: light.fastled_light
    domain: light
 # added push notification to mobile phone (Home Assistant app installed)
 # need to update with your mobile device ID
  - service: notify.mobile_app_<your_phone_ID>
    data:
      message: Plant watering automation triggered
      title: Watering Triggered
mode: single
